// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoKCR.DAL;

#nullable disable

namespace ProyectoKCR.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ProyectoKCR.Models.Clientes", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("ProyectoKCR.Models.DetallePreFactura", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPreFactura")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitarioHistorico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicio")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdPreFactura");

                    b.ToTable("detallePreFactura");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Empleados", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEmpleado");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Materiales", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMaterial");

                    b.ToTable("materiales");

                    b.HasData(
                        new
                        {
                            IdMaterial = 1,
                            Existencia = 100,
                            Nombre = "Papel",
                            PrecioUnitario = 5m
                        });
                });

            modelBuilder.Entity("ProyectoKCR.Models.PreFacturas", b =>
                {
                    b.Property<int>("IdPreFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPreFactura");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("preFacturas");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Turnos", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumTurno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicio")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdCliente");

                    b.ToTable("turnos");
                });

            modelBuilder.Entity("ProyectoKCR.Models.DetallePreFactura", b =>
                {
                    b.HasOne("ProyectoKCR.Models.Materiales", "Material")
                        .WithMany("DetallesPreFactura")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoKCR.Models.PreFacturas", "PreFactura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPreFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("PreFactura");
                });

            modelBuilder.Entity("ProyectoKCR.Models.PreFacturas", b =>
                {
                    b.HasOne("ProyectoKCR.Models.Clientes", "Cliente")
                        .WithMany("PreFacturas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoKCR.Models.Empleados", "Empleado")
                        .WithMany("preFacturas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Turnos", b =>
                {
                    b.HasOne("ProyectoKCR.Models.Clientes", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Clientes", b =>
                {
                    b.Navigation("PreFacturas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Empleados", b =>
                {
                    b.Navigation("preFacturas");
                });

            modelBuilder.Entity("ProyectoKCR.Models.Materiales", b =>
                {
                    b.Navigation("DetallesPreFactura");
                });

            modelBuilder.Entity("ProyectoKCR.Models.PreFacturas", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
